### ISSUE TITLE
task datasets link 

### ISSUE THREAD

**Issue by Bailey-24** [Selina2023/Open6DOR#1]

**Comment by Selina2023** [comment]
Yes, the task dataset is currently not publicly available. We will release the final version of the benchmark along with our refined method in early September, shortly after the camera-ready paper is published. Thanks for the reminder!

**Comment by zubair-irshad** [comment]
Are these planned to be released soon? Thanks for your great work!

**Comment by geng-haoran** [comment]
Please check the readme for the task dataset. Already updated!
